<?php
/*
function gsapp_tutorials_api_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items){
  foreach ($entities as $id => $entity) {
    if (empty($items[$id]) && $field['settings']['default_image']) {
      if ($file = file_load($field['settings']['default_image'])) {
        $items[$id][0] = (array) $file + array(
          'is_default' => TRUE, 
          'alt' => '', 
          'title' => '',
        );
      }
    }
  }


}*/

function gsapp_tutorials_api_node_view($node, $view_mode, $langcode) {

  if ($node->type == 'tutorial') {
    
    $question_answer_data = array();
    
    watchdog('gsapp', 'recreating data structure');



    foreach($node->field_questions_reference['und'] as $key=>$value) {
      watchdog('gsapp', 'iterating through questions ref ' . $key);      
      $q_node = $value['node'];
      watchdog('gsapp', 'iterating through questions value is ' . serialize($q_node));

      $question_data = array(
        'nid'       => $q_node->nid,
        'dom_id'    => 'q-' . $q_node->nid,
        'title'     => $q_node->title,
        'body'      => (@strlen($q_node->field_description['und'][0]['safe_value'] > 0) ? $q_node->field_description['und'][0]['safe_value'] : ''),
        'uid'       => $q_node->uid,
        'username'  => $q_node->name,
        'created'    => $q_node->created,
        'answers'   => array()
      );
      watchdog("gsapp", "----------------------------------------------------");
      watchdog("gsapp", 'question data is ' . serialize($question_data));


      if (@count($q_node->field_answers_reference['und']) > 0) {
        watchdog('gsapp', 'looking at answers');
        $answer_nids = $q_node->field_answers_reference['und'];
        foreach($answer_nids as $answer) {
          $answer_node = node_load($answer['nid'], NULL, True);
          $question_data['answers'][] = array(
            'answer_nid'    => $answer_node->nid,
            'dom_nid'       => 'a-' . $answer_node->nid,
            'body'          => (@strlen($answer_node->body['und'][0]['safe_value']) > 0 ? $answer_node->body['und'][0]['safe_value'] : ''),
            'uid'           => $answer_node->uid,
            'username'      => $answer_node->name,
            'created'       => $answer_node->created
          );
        }
        
      }
      $question_answer_data[] = $question_data;
    }
    watchdog('gsapp', 'final struct is ' . serialize($question_answer_data));
    $node->content['field_qa_data']['und'][0]['value'] = serialize($question_answer_data);
  }
}


