<?php



function gsapp_tutorials_api_node_view($node, $view_mode, $langcode) {

  //$node->content['foobar'] = 88;
//  $strBody = $node->content['body'][0]['#markup'];
  //$node->content['body'][0]['#markup'] = 'gsapp additional text' . $strBody;


  // get answers from DB 
  
  $nid = $node->nid;

  $result = db_query('SELECT n.field_questions_reference_nid
                      FROM {field_data_field_questions_reference} n WHERE n.entity_id = :eid', array(':eid' => $nid));
  

  $question_nodes = array();
  
  foreach ($result as $record) {
    $n_temp = node_load($record->field_questions_reference_nid, NULL, True);
    $question_nodes[] = $n_temp;
  }


  $node->content['field_qa_data']['und'][0]['value'] = 'bar';




  //$node->content['question_nodes'] = $question_nodes;


  




}
